name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER  }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD  }}
      run: | # this symbol "|" means that every line below is a command to run
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build docker Image
      run: |
        docker build -t chavin/docker-graphql:0.0.2 .
        docker build -t chavin/docker-graphql:latest .
    - name: Push docker Image
      run: |
        docker push chavin/docker-graphql:0.0.2
         docker push chavin/docker-graphql:latest
